/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_yyh_com_mycptojavanative_jni_ServiceProvider */

#ifndef _Included_jni_yyh_com_mycptojavanative_jni_ServiceProvider
#define _Included_jni_yyh_com_mycptojavanative_jni_ServiceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_yyh_com_mycptojavanative_jni_ServiceProvider
 * Method:    callFromCMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_yyh_com_mycptojavanative_jni_ServiceProvider_callFromCMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
